alter function public.touch_updated_at() set search_path = public;

revoke execute on function public.current_app_role() from public, anon, authenticated;
revoke execute on function public.is_admin() from public, anon, authenticated;
revoke execute on function public.can_read_student(uuid) from public, anon, authenticated;
revoke execute on function public.can_review_student(uuid) from public, anon, authenticated;
revoke execute on function public.handle_new_auth_user() from public, anon, authenticated;
revoke execute on function public.touch_updated_at() from public, anon, authenticated;

create index if not exists guardianships_parent_id_idx on public.guardianships(parent_id);
create index if not exists cohort_students_student_id_idx on public.cohort_students(student_id);
create index if not exists cohort_tutors_tutor_id_idx on public.cohort_tutors(tutor_id);
create index if not exists skill_domains_capability_id_idx on public.skill_domains(capability_id);
create index if not exists skills_domain_id_idx on public.skills(domain_id);
create index if not exists competencies_skill_id_idx on public.competencies(skill_id);
create index if not exists mission_skills_skill_id_idx on public.mission_skills(skill_id);
create index if not exists mission_prerequisites_required_competency_id_idx on public.mission_prerequisites(required_competency_id);
create index if not exists lessons_mission_stage_id_idx on public.lessons(mission_stage_id);
create index if not exists activities_lesson_id_idx on public.activities(lesson_id);
create index if not exists resources_mission_id_idx on public.resources(mission_id);
create index if not exists resources_lesson_id_idx on public.resources(lesson_id);
create index if not exists placement_results_student_id_idx on public.placement_results(student_id);
create index if not exists student_competencies_competency_id_idx on public.student_competencies(competency_id);
create index if not exists student_skill_progress_skill_id_idx on public.student_skill_progress(skill_id);
create index if not exists submissions_student_id_idx on public.submissions(student_id);
create index if not exists submissions_mission_id_idx on public.submissions(mission_id);
create index if not exists evidence_items_student_id_idx on public.evidence_items(student_id);
create index if not exists evidence_items_submission_id_idx on public.evidence_items(submission_id);
create index if not exists evidence_items_mission_id_idx on public.evidence_items(mission_id);
create index if not exists submission_revisions_submission_id_idx on public.submission_revisions(submission_id);
create index if not exists submission_revisions_student_id_idx on public.submission_revisions(student_id);
create index if not exists feedback_submission_id_idx on public.feedback(submission_id);
create index if not exists feedback_tutor_id_idx on public.feedback(tutor_id);
create index if not exists feedback_scores_feedback_id_idx on public.feedback_scores(feedback_id);
create index if not exists badges_capability_id_idx on public.badges(capability_id);
create index if not exists student_badges_badge_id_idx on public.student_badges(badge_id);
create index if not exists student_badges_awarded_by_idx on public.student_badges(awarded_by);
create index if not exists student_badges_evidence_item_id_idx on public.student_badges(evidence_item_id);
create index if not exists portfolio_items_student_id_idx on public.portfolio_items(student_id);
create index if not exists portfolio_items_submission_id_idx on public.portfolio_items(submission_id);
create index if not exists ai_interactions_student_id_idx on public.ai_interactions(student_id);
create index if not exists ai_interactions_mission_id_idx on public.ai_interactions(mission_id);
create index if not exists attendance_student_id_idx on public.attendance(student_id);
create index if not exists reflections_student_id_idx on public.reflections(student_id);
create index if not exists reflections_mission_id_idx on public.reflections(mission_id);
create index if not exists safety_flags_student_id_idx on public.safety_flags(student_id);
create index if not exists safety_flags_raised_by_idx on public.safety_flags(raised_by);
create index if not exists audit_log_actor_id_idx on public.audit_log(actor_id);
